from enum import Enum

class UserRole(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    COLLEGE_REP = "COLLEGE_REP"
    FACULTY_COORDINATOR = "FACULTY_COORDINATOR"
    PRESIDENT = "PRESIDENT"
    VICE_PRESIDENT = "VICE_PRESIDENT"
    DEPARTMENT_LEAD = "DEPARTMENT_LEAD"
    MEMBER = "MEMBER"